/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(hnchbbboard_source.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(de40fb37a0cc248a570f3a214f0d0d6f)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <iio/hnchbbboard_source.h>
// pydoc.h is automatically generated in the build directory
#include <hnchbbboard_source_pydoc.h>

void bind_hnchbbboard_source(py::module& m)
{

    using hnchbbboard_source    = ::gr::iio::hnchbbboard_source;
    using hnchbbboard_source_f32c    = ::gr::iio::hnchbbboard_source_f32c;


    py::class_<hnchbbboard_source, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<hnchbbboard_source>>(m, "hnchbbboard_source", D(hnchbbboard_source))

        .def(py::init(&hnchbbboard_source::make),
           py::arg("uri"),
           py::arg("frequency"),
           py::arg("samplerate"),
           py::arg("stream_id"),
           py::arg("buffer_size"),
           py::arg("gain_value"),
           D(hnchbbboard_source,make)
        )
        .def("set_params",&hnchbbboard_source::set_params,       
            py::arg("frequency"),
            py::arg("samplerate"),
            py::arg("gain_value"),
            D(hnchbbboard_source,set_params)
        )
        ;


    py::class_<hnchbbboard_source_f32c, gr::hier_block2,
        std::shared_ptr<hnchbbboard_source_f32c>>(m, "hnchbbboard_source_f32c", D(hnchbbboard_source_f32c))

        .def(py::init(&hnchbbboard_source_f32c::make),
           py::arg("uri"),
           py::arg("frequency"),
           py::arg("samplerate"),
           py::arg("stream_id"),
           py::arg("buffer_size"),
           py::arg("gain_value"),
           D(hnchbbboard_source_f32c,make)
        )
        




        
        .def("set_params",&hnchbbboard_source_f32c::set_params,       
            py::arg("frequency"),
            py::arg("samplerate"),
            py::arg("gain_value"),
            D(hnchbbboard_source_f32c,set_params)
        )

        ;




}








